wip: add sqlite backend for the taskqueue
kalbhor/Tasqueue pull request #42
Opened 2023-09-22 18:52 UTC by dineshsalunke

2023-09-25 05:30 UTC, kalbhor commented
Hey, a sqlite results store would be quite useful. I see you're interested, do let me know if any help needed

2023-09-29 08:39 UTC, dineshsalunke commented
@kalbhor First of all sorry for the late response. we are surely interested in finishing this up, and for sure would need help on it ( We are just starting up on go ).

Will put out our ideas here so that we can brainstorm and clear our doubt's.

** Also I am saying we coz our team will be working on this as well, they will chime in soon

2023-10-01 08:02 UTC, dineshsalunke commented
@kalbhor done with initial implementation for the enqueuing and consuming with sqlite3, check it once and let me know your thoughts. If everything seems ok then will move forward with rest of implementation

2023-10-03 13:56 UTC, kalbhor commented
hey, sorry for the delay. Glanced at this and it looks good. Please give me few days to give a detailed review

2023-10-10 16:17 UTC, kalbhor requested changes
Left some review comments. Overall, the implementation looks good, just need to modify certain things according to how the library expects. We can have another review in the end to go into particulars like Go best practices, etc. Cheers :tada:

2025-07-01 06:10 UTC, closed without merging